on: [push]

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./.github/actions/install
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: /github/workspace

  deploy_job:
    name: Deploy
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
      - uses: ./.github/actions/deploy
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
