on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Job to deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: ../actions/deploy
